services:
  orders:
    build:
      target: development
    command: pnpm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WEBPACK_DEV_SERVER_DISABLE_HOST_CHECK=true
      - FAST_REFRESH=false
      - NODE_ENV=development
    tty: true
